# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'FitnessBarz' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SVProgressHUD'

  # Pods for FitnessBarz

  target 'FitnessBarzTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FitnessBarzUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
